# Generated by Django 3.1.5 on 2021-01-09 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('contestId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='DEFAULT-CONTEST', max_length=50)),
                ('description', models.CharField(default='Default Contest description', max_length=1000)),
                ('startTime', models.DateField()),
                ('endTime', models.DateField()),
                ('isPrivate', models.BooleanField(default=True)),
                ('registeredUsersCount', models.IntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('EASY', 'EASY'), ('MEDIUM', 'MEDIUM'), ('HARD', 'HARD')], max_length=6)),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
            ],
        ),
    ]
