# Generated by Django 3.1.5 on 2021-01-09 16:59

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210109_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(default='profiles/default.png', upload_to=users.models.get_file_path),
        ),
    ]
