# Generated by Django 3.1.5 on 2021-01-24 13:12

from django.db import migrations, models
import problem.models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20210113_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='inputFile',
            field=models.FileField(max_length=254, upload_to=problem.models.testCaseFileName),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='outputFile',
            field=models.FileField(max_length=254, upload_to=problem.models.testCaseFileName),
        ),
    ]
