# Generated by Django 3.1.5 on 2021-01-25 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20210121_1704'),
        ('lab', '0003_auto_20210121_1256'),
        ('problem', '0004_auto_20210124_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.contest'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.lab'),
        ),
    ]
