# Generated by Django 3.1.5 on 2021-01-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20210125_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='doesBelongToContest',
            field=models.BooleanField(),
        ),
    ]
