# Generated by Django 3.1.5 on 2021-01-28 21:34

from django.db import migrations, models
import problem.models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_auto_20210125_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='inputFile',
            field=models.FileField(max_length=254, upload_to=problem.models.testCaseInputFileName, validators=[problem.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='outputFile',
            field=models.FileField(max_length=254, upload_to=problem.models.testCaseOutputFileName, validators=[problem.models.validate_file_extension]),
        ),
    ]
