# Generated by Django 3.1.5 on 2021-01-28 22:11

import django.core.validators
from django.db import migrations, models
import problem.models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0007_auto_20210129_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='inputFile',
            field=models.FileField(max_length=254, upload_to=problem.models.testCaseInputFileName, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])]),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='outputFile',
            field=models.FileField(max_length=254, upload_to=problem.models.testCaseOutputFileName, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml'])]),
        ),
    ]
