# Generated by Django 3.1.5 on 2021-01-28 22:27

import django.core.validators
from django.db import migrations, models
import problem.models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0009_auto_20210129_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='inputFile',
            field=models.FileField(upload_to=problem.models.testCaseInputFileName, validators=[django.core.validators.FileExtensionValidator(['txt'])]),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='outputFile',
            field=models.FileField(upload_to=problem.models.testCaseOutputFileName, validators=[django.core.validators.FileExtensionValidator(['txt'])]),
        ),
    ]
