# Generated by Django 3.1.5 on 2021-01-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blogId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='DEFAULT-BLOG', max_length=50)),
                ('description', models.CharField(default='Default Blog description', max_length=1000)),
                ('attachmentPath', models.FileField(max_length=254, upload_to='blogs/')),
            ],
        ),
    ]
