# Generated by Django 3.1.5 on 2021-01-12 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210112_1013'),
        ('blog', '0005_auto_20210112_1014'),
    ]

    operations = [
    ]
