# Generated by Django 3.1.5 on 2021-01-13 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_merge_20210112_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='userId',
            new_name='user',
        ),
    ]
