# Generated by Django 3.1.5 on 2021-02-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210113_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='attachmentPath',
        ),
    ]
