# Generated by Django 3.1.5 on 2021-02-24 10:58

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_remove_blog_attachmentpath'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComments',
            fields=[
                ('bcId', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=2000)),
                ('attachmentPath', models.FileField(blank=True, max_length=254, null=True, upload_to=blog.models.blogAttachmentFileName)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
