# Generated by Django 3.1.5 on 2021-01-09 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='DEFAULT-CLASS', max_length=50)),
                ('description', models.CharField(default='Default description', max_length=1000)),
                ('semester', models.IntegerField(default=-1)),
                ('year', models.IntegerField(default=-1)),
                ('classroomCode', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('branch', models.CharField(default='Default branch', max_length=50)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassComments',
            fields=[
                ('ccId', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=2000)),
                ('attachmentPath', models.FileField(max_length=254, upload_to='classAttachments/')),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
