# Generated by Django 3.1.5 on 2021-02-16 08:32

import classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_classroomstudents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcomments',
            name='attachmentPath',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=classroom.models.classAttachmentFileName),
        ),
    ]
