# Generated by Django 3.1.5 on 2021-01-09 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submissionId', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('status', models.BooleanField()),
                ('filePath', models.FileField(max_length=256, upload_to='submissions/')),
                ('submissionTime', models.DateTimeField(auto_now=True)),
                ('problemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewId', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=1000)),
                ('submissionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.submission')),
            ],
        ),
    ]
