# Generated by Django 3.1.5 on 2021-01-13 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='submissionId',
            new_name='submission',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='problemId',
            new_name='problem',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='userId',
            new_name='user',
        ),
    ]
