# Generated by Django 3.1.5 on 2021-02-15 16:55

import django.core.validators
from django.db import migrations, models
import submissions.models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_auto_20210113_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='filePath',
            field=models.FileField(max_length=256, upload_to=submissions.models.submissionFileName, validators=[django.core.validators.FileExtensionValidator(['c'])]),
        ),
    ]
