# Generated by Django 3.1.5 on 2021-02-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_auto_20210215_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='filePath',
            field=models.CharField(max_length=1000),
        ),
    ]
