# Generated by Django 3.1.5 on 2021-01-13 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='classId',
            new_name='classroom',
        ),
    ]
