# Generated by Django 3.1.5 on 2021-01-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_auto_20210113_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='title',
            field=models.CharField(default='Default lab title', max_length=10),
        ),
        migrations.AlterField(
            model_name='lab',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
