# Generated by Django 3.1.5 on 2021-02-19 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab', '0003_auto_20210121_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabGrade',
            fields=[
                ('labGradeId', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(default='F', max_length=1)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.lab')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
